pub mod daemon;
pub mod robot;

// match to this:
/*
export const keyboardButtons = {
  a: 0,
  b: 1,
  c: 2,
  d: 3,
  e: 4,
  f: 5,
  g: 6,
  h: 7,
  i: 8,
  j: 9,
  k: 10,
  l: 11,
  m: 12,
  n: 13,
  o: 14,
  p: 15,
  q: 16,
  r: 17,
  s: 18,
  t: 19,
  u: 20,
  v: 21,
  w: 22,
  x: 23,
  y: 24,
  z: 25,
  '1': 26,
  '2': 27,
  '3': 28,
  '4': 29,
  '5': 30,
  '6': 31,
  '7': 32,
  '8': 33,
  '9': 34,
  '0': 35,
  ',': 36,
  '.': 37,
  '/': 38,
  ';': 39,
  "'": 40,
  '[': 41,
  ']': 42,
  ArrowLeft: 43,
  ArrowRight: 44,
  ArrowUp: 45,
  ArrowDown: 46
};
 */
pub mod keymap {
  use gilrs::Button;
  use termion::event::Key;
  pub fn gamepad_mapped(button: &Button) -> u8 {
    return match button {
      Button::DPadUp => 12,
      Button::DPadDown => 13,
      Button::DPadLeft => 14,
      Button::DPadRight => 15,
      Button::Start => 9,
      // Button:: => 5,
      Button::LeftThumb => 4,
      Button::RightThumb => 5,
      Button::LeftTrigger => 6,
      Button::RightTrigger => 7,
      // Button::Guide => 10,
      Button::South => 0,
      Button::East => 1,
      Button::West => 2,
      Button::North => 3,
      _ => 255, // Default case for unmapped buttons
    } 
  }
  pub fn key_map(key: &Key) -> u8 {
    match key {
      Key::Char('a') => 0,
      Key::Char('b') => 1,
      Key::Char('c') => 2,
      Key::Char('d') => 3,
      Key::Char('e') => 4,
      Key::Char('f') => 5,
      Key::Char('g') => 6,
      Key::Char('h') => 7,
      Key::Char('i') => 8,
      Key::Char('j') => 9,
      Key::Char('k') => 10,
      Key::Char('l') => 11,
      Key::Char('m') => 12,
      Key::Char('n') => 13,
      Key::Char('o') => 14,
      Key::Char('p') => 15,
      Key::Char('q') => 16,
      Key::Char('r') => 17,
      Key::Char('s') => 18,
      Key::Char('t') => 19,
      Key::Char('u') => 20,
      Key::Char('v') => 21,
      Key::Char('w') => 22,
      Key::Char('x') => 23,
      Key::Char('y') => 24,
      Key::Char('z') => 25,
      Key::Char('1') => 26,
      Key::Char('2') => 27,
      Key::Char('3') => 28,
      Key::Char('4') => 29,
      Key::Char('5') => 30,
      Key::Char('6') => 31,
      Key::Char('7') => 32,
      Key::Char('8') => 33,
      Key::Char('9') => 34,
      Key::Char('0') => 35,
      Key::Char(',') => 36,
      Key::Char('.') => 37,
      Key::Char('/') => 38,
      Key::Char(';') => 39,
      Key::Char('\'') => 40,
      Key::Char('[') => 41,
      Key::Char(']') => 42,
      Key::Left => 43,
      Key::Right => 44,
      Key::Up => 45,
      Key::Down => 46,
      _ => 255, // Default case for unmapped keys
    }
  }
}